version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
    - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
  redis:
    image: redis:alpine
    restart: always
    volumes:
    - redis_data:/data
  www:
    image: iget/magento-www:latest
    depends_on:
    - mysql
    - redis
    restart: always
    volumes:
    - ../../src:/var/www/
    ports:
    - "8889:80"
    - "35729:35729"

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local